version: "2.24.3"

networks:
    curso_laravel_network:
        name: curso_laravel_network

services:
    php-apache:
        image: webdevops/php-apache-dev:8.2-alpine
        container_name: api-laravel-back
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
        depends_on:
            - mysql-db
        networks:
            curso_laravel_network:
                aliases:
                    - api-laravel-back

    mysql-db:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}

        networks:
            curso_laravel_network:
                aliases:
                    - mysql-db

    portainer:
        image: portainer/portainer
        container_name: portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer_data:/data
